name: Image Scan
on:
  workflow_run:
    workflows: ["Build and Publish docker image"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  
  scan_image:
    name: Scan Image
    runs-on: ubuntu-latest
    steps:
      - name: Trivy Vulnerability Scanner
        # 0.33.1
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
        with:
          image-ref: ghcr.io/${{ github.repository }}:${{ github.sha }} 
          format: "table"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
